name: BuildSamples

on:
  workflow_call:
    inputs:
      solution:
        description: 
        required: true
        type: string

permissions:
  contents: write
  actions: read
  checks: write
  pull-requests: write
  security-events: write 

defaults:
  run:
    shell: pwsh
    
env:
  GITHUB_BRANCH: ${{ github.head_ref || github.ref_name }}
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: 'Any CPU'
  BUILD_SOLUTION: ${{ inputs.solution }}

jobs:
  build-samples:
    name: Build Samples
    runs-on: windows-latest

    strategy:
      fail-fast: false

    steps:
      - name: Print branch
        run: echo $env:GITHUB_BRANCH

      - name: Checkout source
        uses: actions/checkout@v4

      # Restore and build
      - name: Restore dependencies
        run: dotnet restore ${{ env.BUILD_SOLUTION }}

      - name: Setup Visual Studio
        uses: microsoft/setup-msbuild@v1

      - name: Build solution
        run: msbuild ${{ env.BUILD_SOLUTION }} -p:configuration=Release -restore:True
